application: jars-multrates
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /jspsych-6
  static_dir: jspsych-6

- url: /wtf
  static_dir:  wtf

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on
